name: Publish
on:
    workflow_run:
        workflows: [CI]
        types:
        - completed
        branches:
        - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Pull Request 
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}